export function AppFooter() {
  return (
    <footer className="bg-card/50 border-t">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="space-y-4">
            <h3 className="font-semibold">DePIN Network</h3>
            <p className="text-sm text-muted-foreground">
              Decentralized Physical Infrastructure Network powered by Solana blockchain.
            </p>
          </div>
          
          <div className="space-y-4">
            <h4 className="font-medium">Resources</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="https://solana.com/docs" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  Documentation
                </a>
              </li>
              <li>
                <a href="https://github.com/solana-foundation" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  GitHub
                </a>
              </li>
              <li>
                <a href="https://solana.com/developers" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  Developers
                </a>
              </li>
            </ul>
          </div>
          
          <div className="space-y-4">
            <h4 className="font-medium">Community</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="https://discord.gg/solana" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  Discord
                </a>
              </li>
              <li>
                <a href="https://twitter.com/solana" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  Twitter
                </a>
              </li>
              <li>
                <a href="https://solana.stackexchange.com/" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-foreground">
                  Stack Exchange
                </a>
              </li>
            </ul>
          </div>
          
          <div className="space-y-4">
            <h4 className="font-medium">Network Stats</h4>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Active Nodes:</span>
                <span>9,234</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Coverage:</span>
                <span>78.5%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Total Rewards:</span>
                <span>2.8M MAP</span>
              </div>
            </div>
          </div>
        </div>
        
        <div className="mt-8 pt-8 border-t text-center text-sm text-muted-foreground">
          <p>
            Generated by{' '}
            <a href="https://github.com/solana-foundation/create-solana-dapp" target="_blank" rel="noopener noreferrer" className="hover:text-foreground">
              create-solana-dapp
            </a>
            {' '} • Built with ❤️ for the Solana ecosystem
          </p>
        </div>
      </div>
    </footer>
  )
}
